question_data = [
{"text": "La construcción de la torre Eiffel se completó el 31 de marzo de 1887", "answer": "False"},
{"text": "Los relámpagos se ven antes de escucharse porque la luz viaja más rápido que el sonido.", "answer": "True"},
{"text": "La Ciudad del Vaticano es un país.", "answer": "True"},
{"text": "Melbourne es la capital de Australia.", "answer": "False"},
{"text": "La penicilina fue descubierta en Vietnam para tratar la malaria.", "answer": "False"},
{"text": "El monte Fuji es la montaña más alta de Japón.", "answer": "True"},
{"text": "El brócoli contiene más vitamina C que los limones.", "answer": "True"},
{"text": "El cráneo es el hueso más fuerte del cuerpo humano", "answer": "False"},
{"text": "Las bombillas fueron invención de Thomas Edison.", "answer": "False"},
{"text": "Google inicialmente se llamaba BackRub.", "answer": "True"},
{"text": "La caja negra en un avión es negra.", "answer": "False"},
{"text": "Los tomates son frutas.", "answer": "True"},
{"text": "La atmósfera de Mercurio está compuesta de dióxido de carbono.", "answer": "False"},
{"text": "La depresión es la principal causa de discapacidad en todo el mundo.", "answer": "True"},
{"text": "Cleopatra era de ascendencia egipcia.", "answer": "False"},
{"text": "Puedes estornudar mientras duermes.", "answer": "False"},
{"text": "La mucosidad es saludable para tu cuerpo.", "answer": "True"},
{"text": "Tu nariz produce casi un litro de mucosidad al día.", "answer": "True"},
{"text": "Si sumas los dos números en los lados opuestos de los dados, la respuesta siempre es 7.", "answer": "True"},
{"text": "Es imposible estornudar mientras abres los ojos.", "answer": "True"},
]
